# Numpy

In [ ]:
!pip install numpy # 넘파이 사용하기 위한 패키지 설치 (코랩 환경에서 생략 가능), ! : 로컬말고 ...

In [ ]:
import numpy as np # 사용할 패키지 불러오기
print(np.__version__) # 버전이 달라서 안 되는 경우 있기 때문에 확인. + docs 확인.

1.21.6


## 2. 다차원 배열 (N-Dimensional Array) 생성

### 1-D Array 생성



In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


### 2-D Array 생성

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)
print(type(arr))
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
(2, 4)


### 3-D Array 생성

In [ ]:
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],
                [[9, 10, 11, 12], [13, 14, 15, 16]],
                [[17, 18, 19, 20], [21, 22, 23, 24]]])

print(arr)
print(type(arr))
print(arr.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
<class 'numpy.ndarray'>
(3, 2, 4)


## 3. 배열의 속성

In [ ]:
# 빠르게 데이터 구조를 파악할 때
arr.shape 

(3, 2, 4)

In [ ]:
# 차원 갯수 확인
arr.ndim 

3

In [ ]:
# 전체 데이터(원소) 개수 확인
arr.size

24

In [ ]:
# 데이터 타입 확인
arr.dtype

dtype('int64')

In [ ]:
# ex. 3차원 데이터에서는 2차원 데이터 하나하나가 아이템!
arr.itemsize

8

## 4. 배열의 자료형 (Data Type)

In [ ]:
# 명시적으로 자료형 지정
arr = np.array([1, 2, 3], dtype=np.float64)

## 5. 배열의 형태(Shape)와 축(Axis)

## 6. 배열 생성함수

In [ ]:
arr = np.arange(0, 10001, 5)
print(arr.shape)

(2001,)


In [ ]:
np.linspace(0, 4, 5)

array([0., 1., 2., 3., 4.])

In [ ]:
np.linspace(0, 4, 3)

array([0., 2., 4.])

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0, 100, 20) # min 0에서 max 100 안의, 일정한 값들을 필요로 할 때

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [ ]:
np.zeros((2, 3))

# * (2,3) 을 튜플로 받아감!

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3, 2, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.full((2, 3), 5.0)

array([[5., 5., 5.],
       [5., 5., 5.]])

## 추가

In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

In [ ]:
a2 = np.array([ [1,2,3], [4,5,6], [7,8,9]])
print(a2)
print(a2.shape)
print(a2[0,0], a2[1, 1], a2[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [ ]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
             [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
             [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### eye

In [ ]:
# eye() : 단위행렬(identity matrix) 생성
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### tri

In [ ]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

### empty

In [ ]:
np.empty(10)

array([3.38329514e-316, 1.77863633e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.22309266e+161, 5.92934620e-038, 6.81518361e-091,
       1.25581582e-071, 4.24373103e-315])

In [ ]:
print(a1)

[4 5 6 4 5]


### like

In [ ]:
np.zeros_like(a1) # a1 과 자릿수가 똑같은 행렬이 0으로 초기화되어 만들어짐.

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros_like(a2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.full_like(a3, 10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### random

In [ ]:
np.random.random((3, 3))

array([[0.92847266, 0.66982719, 0.43979053],
       [0.32961728, 0.24375423, 0.66235165],
       [0.86374113, 0.33952094, 0.76736192]])

In [ ]:
np.random.randint(0, 10, (3, 3))

array([[0, 5, 2],
       [6, 6, 8],
       [9, 9, 1]])

In [ ]:
np.random.normal(0, 1, (3, 3)) # 정규분포를 고려한 랜덤한 수의 배열 생성, 평균 = 0, 표준편차 = 1.3 * 3 배열

array([[ 0.58200513, -0.81838983,  1.87163284],
       [-2.23865225,  0.53169764,  0.4140869 ],
       [ 0.2061664 ,  2.06779136,  0.41011321]])

In [ ]:
np.random.rand(3, 3) # 균등분포를 고려한 랜덤한 수의 배열 생성

array([[0.28512384, 0.41890424, 0.0195678 ],
       [0.34358843, 0.16744489, 0.34482238],
       [0.38594809, 0.48748505, 0.35481209]])

In [ ]:
# 표준 정규 분포를 고려한 랜덤한 수의 배열 생성
np.random.randn(3, 3)

array([[-1.00024492,  0.45781263,  1.25900942],
       [ 0.95819174, -1.51542518, -0.10888116],
       [ 0.15817179, -0.16681152, -0.47257975]])

### ones, dtype=bool

In [ ]:
np.ones((3, 3), dtype=bool)

# 예를 들어.. 데이터를 수집했을 때, 들어온 데이터에 값이 있으면 True, 없으면 False. -> 문제가 되는 데이터들을 추출할 수 있는 방법.

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

###넘파이(Numpy)에서 날짜와 시간
넘파이에서 날짜와 시간은 datetime64 객체로 표현한다. 기존 파이썬의 datetime.datetime과 넘파이의 datetime64의 차이점은 시간 단위이다. datetime.datetime은 시간을 마이크로초(10-6)단위까지 관리하며, 넘파이의 datetime64는 아토초(10-18)단위까지 관리한다

In [ ]:
import numpy as np
np.datetime64('2021-12-21') # 문자열 형식으로 전달해서 생성하는 방법

In [ ]:
import numpy as np
np.datetime64(1000,'ns')		#나노초
np.datetime64(10000,'D')		#일
np.datetime64(1000000000,'s')	#초
# 유닉스 시간을 이용하는 방법
# np.datetime64함수의 첫번째 인자로 수치 데이터를, 두번째 인자로 단위를 넣어주면 된다.

In [ ]:
import numpy as np
np.array(['2000-05-05', '2007-01-11', '2013-08-15'], dtype='datetime64')
# array()함수를 사용하는 방법
# np.array()함수에 첫번째 인자로 str타입의 날짜 리스트를 넣고, 두번째 인자로 dtype(데이터 타입)을 'datetime64'로 설정하면 첫번째 인자로 넣은 리스트의 타입이 날짜로 변경된다.

In [ ]:
import numpy as np
np.arange('2005-05', '2006-02', dtype='datetime64[M]') # 월단위
# arange()함수를 사용해 범위를 통해 날짜를 생성하는 방법
# np.arange()함수에 첫번째 인자로는 시작하는 날짜, 두번째 인자로는 종료하는 날짜, 마지막 인자로 dtype을 넣어주면 주어진 범위에 맞는 날짜 배열을 생성한다. dtype의 경우 방법3에서 설명한 것처럼 '[]'안에 어떤 값을 넣는지에 따라 날짜 단위를 지정할 수 있다.

**단위코드**<br>
Y : 년<br>
M : 월<br>
W : 주<br>
D : 일<br>
h : 시간<br>
m : 분<br>
s : 초<br>
ms : 밀리초<br>
us : 마이크로초<br>
ns : 나노초<br>
ps : 피코초<br>
fs : 펨토초<br>
as : 아토초

In [ ]:
data = np.array('2023-01-01', dtype=np.datetime64)
data

array('2023-01-01', dtype='datetime64[D]')

In [ ]:
data + np.arange(50) # 초기값이 data 가 되고, 나머지는 1단위로 증가. 타입이 날짜이므로, 달도 넘어감. -> 가짜의 날짜 데이터를 만들 수 있음.

array(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
       '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
       '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
       '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
       '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
       '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
       '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
       '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
       '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
       '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
       '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
       '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
       '2023-02-18', '2023-02-19'], dtype='datetime64[D]')

### insert, true/false

In [ ]:
print(a1)

[4 5 6 4 5]


In [ ]:
bi = [False, True, True, False, True]
print(a1[bi]) # True 에 해당하는 idx 의 값만 추출.

[5 6 5]


In [ ]:
b1 = np.insert(a1, 0, 10) # 0번째 idx에 값 10을 넣음.
b1

array([10,  4,  5,  6,  4,  5])